/**
 * Copyright (c) Elastic Path Software Inc., 2013
 */
// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.elasticpath.test.factory;

import com.elasticpath.domain.customer.impl.CustomerCreditCardImpl;

public class CustomerCreditCardBuilder extends CustomerCreditCardImplBuilderBase<CustomerCreditCardBuilder> {
	public static CustomerCreditCardBuilder newCustomerCreditCard() {
		return new CustomerCreditCardBuilder();
	}

	public CustomerCreditCardBuilder() {
		super(new CustomerCreditCardImpl());
	}

	public CustomerCreditCardImpl build() {
		return getInstance();
	}
}

@SuppressWarnings("unchecked")
class CustomerCreditCardImplBuilderBase<GeneratorT extends CustomerCreditCardImplBuilderBase<GeneratorT>> {
	private final CustomerCreditCardImpl instance;

	protected CustomerCreditCardImplBuilderBase(final CustomerCreditCardImpl aInstance) {
		instance = aInstance;
	}

	protected CustomerCreditCardImpl getInstance() {
		return instance;
	}

	public GeneratorT withCardHolderName(final String aValue) {
		instance.setCardHolderName(aValue);

		return (GeneratorT) this;
	}

	public GeneratorT withCardNumber(final String aValue) {
		instance.setCardNumber(aValue);

		return (GeneratorT) this;
	}

	public GeneratorT withCardType(final String aValue) {
		instance.setCardType(aValue);

		return (GeneratorT) this;
	}

	public GeneratorT withExpiryMonth(final String aValue) {
		instance.setExpiryMonth(aValue);

		return (GeneratorT) this;
	}

	public GeneratorT withExpiryYear(final String aValue) {
		instance.setExpiryYear(aValue);

		return (GeneratorT) this;
	}

	public GeneratorT withIssueNumber(final int aValue) {
		instance.setIssueNumber(aValue);

		return (GeneratorT) this;
	}

	public GeneratorT withStartMonth(final String aValue) {
		instance.setStartMonth(aValue);

		return (GeneratorT) this;
	}

	public GeneratorT withStartYear(final String aValue) {
		instance.setStartYear(aValue);

		return (GeneratorT) this;
	}

	public GeneratorT withSecurityCode(final String aValue) {
		instance.setSecurityCode(aValue);

		return (GeneratorT) this;
	}

	public GeneratorT withUidPk(final long aValue) {
		instance.setUidPk(aValue);

		return (GeneratorT) this;
	}

	public GeneratorT withGuid(final String aValue) {
		instance.setGuid(aValue);

		return (GeneratorT) this;
	}

}
