package com.elasticpath.extensions.domain.impl;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

import com.elasticpath.persistence.api.AbstractEntityImpl;
import com.elasticpath.extensions.domain.Example;

/**
 * This is a simple example entity whose schema is generated by the Liquibase archetype that we ship.
 */
@Entity
@Table(name = ExampleImpl.TABLE_NAME)
public class ExampleImpl extends AbstractEntityImpl implements Example {

	/**
	 * When changing this entity; please update its serialVersionUID.
	 */
	public static final long serialVersionUID = 1L;

	private long uidPk;

	private String userName, firstName, lastName;

	private int testId;

	private String guid;

	/**
	 * The name of the table & generator to use for persistence.
	 */
	public static final String TABLE_NAME = "TEXAMPLE";

	@Override
	@Basic(optional = true)
	@Column(name = "FIRSTNAME", nullable = true)
	public String getFirstName() {
		return firstName;
	}

	@Override
	@Basic(optional = true)
	@Column(name = "LASTNAME", nullable = true)
	public String getLastName() {
		return lastName;
	}

	@Override
	@Basic(optional = false)
	@Column(name = "USERNAME", nullable = false)
	public String getUserName() {
		return userName;
	}

	@Override
	public int getTestId() {
		return testId;
	}

	@Override
	@Id
	@Column(name = "UIDPK")
	@GeneratedValue(strategy = GenerationType.TABLE, generator = TABLE_NAME)
	@TableGenerator(name = TABLE_NAME, table = "JPA_GENERATED_KEYS", pkColumnName = "ID", valueColumnName = "LAST_VALUE", pkColumnValue = TABLE_NAME)
	public long getUidPk() {
		return this.uidPk;
	}

	@Override
	@Basic
	@Column(name = "GUID")
	public String getGuid() {
		return guid;
	}

	@Override
	public void setFirstName(final String firstName) {
		this.firstName = firstName;
	}

	@Override
	public void setLastName(final String lastName) {
		this.lastName = lastName;
	}

	@Override
	public void setUserName(final String userName) {
		this.userName = userName;
	}

	@Override
	public void setTestId(final int testId) {
		this.testId = testId;
	}

	@Override
	public void setUidPk(final long uidPk) {
		this.uidPk = uidPk;

	}

	@Override
	public void setGuid(final String guid) {
		this.guid = guid;
	}

}
